verify_added

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -21,11 +21,15 @@ jobs:
           distribution: 'temurin'
           cache: maven
       - name: Build with Maven
+        id: build
         working-directory: ./IndividualProject
         run: mvn -B package --file pom.xml
       - name: Run JUnit tests and verify with Maven
         working-directory: ./IndividualProject
         run: mvn clean test package verify
+      - name: Fail build if there are violations
+        if: steps.build.outputs.violations != 0
+        run: exit 1
       - name: Generate JaCoCo Badge
         id: jacoco
         uses: cicirello/jacoco-badge-generator@v2
@@ -33,13 +37,12 @@ jobs:
           generate-branches-badge: true
           jacoco-csv-file: >
             IndividualProject/target/site/jacoco/jacoco.csv
-      - name: style check
-        id: style_check
-        working-directory: ./IndividualProject
-        run: mvn checkstyle:check
-      - name: Fail build if there are violations
-        if: steps.style_check.outputs.violations != 0
-        run: exit 1
+      #- name: style check
+       # id: style_check
+        #working-directory: ./IndividualProject
+        #run: mvn checkstyle:check
+      #- name: Fail build if there are violation
+        #run: exit 1
       - uses: pmd/pmd-github-action@v2
         id: pmd
         with:
